config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :circuits
  resources :posts
  resources :shops
  get '/', to: 'site#index'
  get '/noticias', to: 'site#posts'
  get '/noticias/:id', to: 'site#post_detail'
  get '/tiendas', to: 'site#shops'
  get '/eventos', to: 'site#events'
  get '/circuits-all', to: 'site#get_circuits'
  post '/circuits-filter', to: 'site#get_circuits_filter'
  get '/shops-all', to: 'site#get_shops'
  post '/shops-filter', to: 'site#get_shops_filter'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.has_role? :admin
      can :manage, :all
    else
      can :create, Circuit
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circuit.rb
class Circuit < ApplicationRecord
  belongs_to :user
  resourcify
  validates :name, :location_x, :location_y, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/insurance.rb
class Insurance < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  resourcify
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :circuits
  has_many :news
  has_many :shops
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
   redirect_to '/', :alert => exception.message
  end

  helper_method :resource, :resource_name, :devise_mapping

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/circuits_controller.rb
class CircuitsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :my_sanitizer
  def index
    @circuits = Circuit.all
  end

  def new
    @circuit = Circuit.new
  end

  def create
     @circuit = Circuit.new(my_sanitizer)
     if @circuit.save
       flash[:notice] = 'El circuito se ha añadido correctamente'
       redirect_to "/circuits/"
     else
       flash[:alert] = @circuit.errors.full_messages
       render 'new'
     end
  end

  def edit
    circuit
  end

  def update
    if circuit.update(my_sanitizer)
      flash[:notice] = 'El circuito se ha modificado correctamente'
      redirect_to "/circuits/"
    else
      flash[:alert] = circuit.errors.full_messages
    end
  end

  private
    def circuit
      @circuit = Circuit.find_by(id: params[:id])
    end
    def my_sanitizer
      params.require(:circuit).permit(:name, :location_x, :location_y, :web,
      :dressing_rooms, :price, :training_classes, :address, :state, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :my_sanitizer
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
     @post = Post.new(my_sanitizer)
     if @post.save
       flash[:notice] = 'La noticia se ha añadido correctamente'
       redirect_to "/posts/"
     else
       flash[:alert] = @post.errors.full_messages
       render 'new'
     end
  end

  def edit
    post
  end

  def update
    if post.update(my_sanitizer)
      flash[:notice] = 'La noticia se ha modificado correctamente'
      redirect_to '/posts/'
    else
      flash[:alert] = Post.errors.full_messages
    end
  end

  def destroy
   if post.present?
     post.destroy
     flash[:notice] = "El post se ha eliminado correctamente"
   else
     flash[:alert] = "El post no existe"
   end
   redirect_to '/posts'
  end

  private
    def post
      @post = Post.find_by(id: params[:id])
    end
    def my_sanitizer
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :my_sanitizer
  def index
    @shops = Shop.all
  end

  def new
    @shop = Shop.new
  end

  def create
     @shop = Shop.new(my_sanitizer)
     if @shop.save
       flash[:notice] = 'La tienda se ha añadido correctamente'
       redirect_to "/shops/"
     else
       flash[:alert] = @shop.errors.full_messages
       render 'new'
     end
  end

  def edit
    shop
  end

  def update
    if shop.update(my_sanitizer)
      flash[:notice] = 'La tienda se ha modificado correctamente'
      redirect_to '/shops/'
    else
      flash[:alert] = Shop.errors.full_messages
    end
  end

  private
    def shop
      @shop = Shop.find_by(id: params[:id])
    end
    def my_sanitizer
      params.require(:shop).permit(:name, :location_x, :location_y, :web, :description,
                                   :user_id, :bicycle_sale, :open_sunday_to_sunday,
                                   :bicycle_rental, :bicycle_repair, :address,
                                   :horary)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @circuits = Circuit.all
  end
  def posts
      @posts = Post.all
      @events = Event.all
  end
  def post_detail
    @post = Post.find_by(id: params[:id])
  end
  def shops
    @shops = Shop.all
  end
  def events
    @events = Event.all
  end
  def get_circuits
    circuits = Circuit.all
    render json: circuits
  end

  def get_circuits_filter
    obj = params[:filter]
    circuits = Circuit.where(decode_json(obj))
    render json: circuits
  end

  def get_shops
    shops = Shop.all
    render json: shops
  end

  def get_shops_filter
    obj = params[:filter]
    circuits = Shop.where(decode_json(obj))
    render json: circuits
  end
private
  def decode_json(obj)
    j = ActiveSupport::JSON
    j.decode(obj)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circuit_helper.rb
module CircuitHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/circuits/_form.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>
<%= form_for [@circuit] do |f| %>
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :name, 'Nombre' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :training_classes, 'Clases de Entrenamiento' %>
        <%= f.select :training_classes,
            options_for_select([
                            ['Si', '1'],
                            ['No', '0'],
                            ]
                          ),
            {}, {class: 'form-control'}
        %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :dressing_rooms, 'Vestuario' %>
        <%= f.select :dressing_rooms,
            options_for_select([
                            ['Si', '1'],
                            ['No', '0'],
                            ]
                          ),
            {}, {class: 'form-control'}
        %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :state, 'Estado' %>
        <%= f.select :state,
            options_for_select([
                            ['Aprobado', '1'],
                            ['Inactivo', '0'],
                            ]
                          ),
            {}, {class: 'form-control'}
        %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :web, 'Web' %>
        <%= f.text_field :web, class: 'form-control', id: 'web' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :price, 'Precio' %>
        <%= f.text_field :price, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :location_x, 'Latitud' %>
        <%= f.text_field :location_x, class: 'form-control', id: 'latitude'  %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :location_y, 'Longitud' %>
        <%= f.text_field :location_y, class: 'form-control', id: 'longitude' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <div id="map_canvas"></div>
        <%= f.text_field :address, class: 'form-control', id: 'address' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= f.button :Guardar, class: 'btn btn-primary' %>
      </div>
    </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
<% end %>

app/views/circuits/edit.html.erb
<% content_for :head_js do %>
  <%= javascript_include_tag 'http://maps.google.com/maps/api/js?key=AIzaSyCzaltzSwfmKs1IbQA0QLNUVfQ8nSsoekg&libraries=places' %>
<% end %>
<section class="page-header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1>Circuitos / Editar</h1>
      </div>
    </div>
  </div>
</section>
<main class="main">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 main-content">
        <div>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</main>
<% content_for :page_js do %>
  <%= javascript_include_tag 'global' %>
  <%= javascript_include_tag 'maps' %>
  <%= javascript_include_tag 'circuits/edit' %>
<% end %>

app/views/circuits/index.html.erb
<% content_for :head_css do %>
  <%= stylesheet_link_tag 'https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css', media: 'all' %>
<% end %>
<% content_for :head_js do %>
  <%= javascript_include_tag 'https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js' %>
  <%= javascript_include_tag 'https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js' %>
<% end %>
<section class="page-header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1>Circuitos</h1>
      </div>
    </div>
  </div>
</section>
<main class="main">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 main-content">
        <div class="item-content">
          <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>
          <div class="form-group">
            <%= link_to new_circuit_path, class: 'btn btn-primary' do %>
              Añadir <i class="fa fa-plus"></i>
            <% end %>
          </div>
          <table id="example" class="display table-border" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Dirección</th>
                    <th>Precio</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <% @circuits.each do |circuit| %>
                  <tr>
                      <td><%= circuit.name %></td>
                      <td><%= circuit.address %></td>
                      <td><%= circuit.price %></td>
                      <td>
                        <a class="btn btn-sm">
                          <i class="fa fa-check-square-o"></i> Aprobar
                        </a>
                        <%= link_to edit_circuit_path(circuit), class: 'btn btn-sm' do %>
                          <i class="fa fa-edit"></i>  Editar
                        <% end %>
                        <a class="btn btn-sm">
                          <i class="fa fa-trash-o"></i> Borrar
                        </a>
                      </td>
                  </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>
<script type="text/javascript">
  $(document).ready(function() {
    $('#example').DataTable();
  });
</script>

app/views/circuits/new.html.erb
<% content_for :head_js do %>
  <%= javascript_include_tag 'http://maps.google.com/maps/api/js?key=AIzaSyCzaltzSwfmKs1IbQA0QLNUVfQ8nSsoekg&libraries=places' %>
<% end %>
<section class="page-header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1>Circuitos / Nuevo</h1>
      </div>
    </div>
  </div>
</section>
<main class="main">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 main-content">
        <div>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</main>
<% content_for :page_js do %>
  <%= javascript_include_tag 'maps' %>
  <%= javascript_include_tag 'circuits/new' %>
<% end %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Bmx Directory</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Khula:400,700" rel="stylesheet">
    <%= yield :head_css %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= yield :head_js %>
  </head>
  <body>
    <!-- Modal -->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Login</h4>
          </div>
          <div class="modal-body">
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
               <div class="form-group">
                <%= f.label :email %><br />
                <%= f.email_field :email, autofocus: true, class: 'form-control' %>
              </div>

               <div class="form-group">
                <%= f.label :password %><br />
                <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
              </div>

              <% if devise_mapping.rememberable? -%>
                 <div class="form-group">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                </div>
              <% end %>

              <div class="actions">
                <%= f.submit "Log in", class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Registro</h4>
          </div>
          <div class="modal-body">
            <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
              <%= devise_error_messages! %>
              <div class="form-group">
                <%= f.label :email %><br />
                <%= f.email_field :email, autofocus: true, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :password %>
                <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
                <% end %><br />
                <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :password_confirmation %><br />
                <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
              </div>

              <div class="actions">
                <%= f.submit "Sign up", class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <header>
      <%= yield :header %>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><%= image_tag("logo.png", size: "100", class: "img-responsive") %></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to 'Inicio', '/' %></li>
              <li><%= link_to 'Noticias', noticias_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Información Útil</a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Tiendas', tiendas_path %></li>

                </ul>
              </li>
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User 1<span class="caret"></span></a>
                  <ul class="dropdown-menu login">
                      <li><a><i class="fa fa-user"></i> Mi perfil</a></li>
                      <% if current_user.has_role? :admin %>
                        <li>
                          <%= link_to circuits_path do %>
                            <i class="fa fa-bicycle"></i> Circuitos
                          <% end %>
                        </li>
                        <li>
                          <%= link_to shops_path do %>
                            <i class="fa fa-bicycle"></i> Tiendas
                          <% end %>
                        </li>
                        <li>
                          <%= link_to posts_path do %>
                            <i class="fa fa fa-newspaper-o"></i> Noticias
                          <% end %>
                        </li>
                      <% else %>
                        <li>
                          <%= link_to new_circuit_path do %>
                            <i class="fa fa-bicycle"></i> Añadir Circuito
                          <% end %>
                        </li>
                        <li>
                          <%= link_to new_shop_path do %>
                            <i class="fa fa-bicycle"></i> Añadir Tienda
                          <% end %>
                        </li>
                        <li>
                          <%= link_to new_post_path do %>
                            <i class="fa fa-newspaper-o"></i> Añadir Noticia
                          <% end %>
                        </li>
                      <% end %>
                      <li>
                        <%= link_to destroy_user_session_path, method: 'DELETE' do %>
                          <i class="fa fa-power-off"></i> Logout
                        <% end %>
                      </li>
                  </ul>
                </li>
              <% else %>
                <li><a data-toggle="modal" data-target="#loginModal"><i class="fa fa-user"></i> Login</a></li>
                <li id="nav-register"><a data-toggle="modal" data-target="#registerModal">/ Registro</a></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    </header>
    <%= yield %>
    <%= yield :page_js %>
    <div class="clr"></div>
    <footer class="nav">
        <div class="copyright col-xs-6">
            Copyright 2017
        </div>
        <div class="social-media-buttons col-xs-6">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-google"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
        </div>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>
<%= form_for [@post] do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title, 'Título' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :state, 'Estado' %>
        <%= f.select :state,
            options_for_select([
                            ['Aprobado', '1'],
                            ['Inactivo', '0'],
                            ]
                          ),
            {}, {class: 'form-control'}
        %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, rows: 50, class: 'form-control'  %>
      </div>
    </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <%= f.button :Guardar, class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<% content_for :head_js do %>
  <%= javascript_include_tag '//cloud.tinymce.com/stable/tinymce.min.js' %>
<% end %>
<section class="page-header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1>Noticias / Editar</h1>
      </div>
    </div>
  </div>
</section>
<main class="main">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 main-content">
        <div class="item-content">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/posts/index.html.erb
<% content_for :head_css do %>
  <%= stylesheet_link_tag 'https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css', media: 'all' %>
<% end %>
<% content_for :head_js do %>
  <%= javascript_include_tag 'https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js' %>
  <%= javascript_include_tag 'https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js' %>
<% end %>
<section class="page-header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1>Noticias</h1>
      </div>
    </div>
  </div>
</section>
<main class="main">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 main-content">
        <div class="item-content">
          <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>
          <div class="form-group">
            <%= link_to new_post_path, class: 'btn btn-primary' do %>
              Añadir <i class="fa fa-plus"></i>
            <% end %>
          </div>
          <table id="example" class="display table-border" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Título</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <% @posts.each do |post| %>
                  <tr>
                      <td><%= post.title %></td>
                      <td>
                        <a class="btn btn-sm">
                          <i class="fa fa-check-square-o"></i> Aprobar
                        </a>
                        <%= link_to edit_post_path(post), class: 'btn btn-sm' do %>
                          <i class="fa fa-edit"></i>  Editar
                        <% end %>
                        <%= link_to 'Borrar', post_path(post),
                            method: :delete, data: { confirm: '¿Estas seguro?'}  %>
                      </td>
                  </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>
<script type="text/javascript">
  $(document).ready(function() {
    $('#example').DataTable();
  });
</script>

app/views/shops/index.html.erb
<% content_for :head_css do %>
  <%= stylesheet_link_tag 'https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css', media: 'all' %>
<% end %>
<% content_for :head_js do %>
  <%= javascript_include_tag 'https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js' %>
  <%= javascript_include_tag 'https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js' %>
<% end %>
<section class="page-header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1>Tiendas</h1>
      </div>
    </div>
  </div>
</section>
<main class="main">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 main-content">
        <div class="item-content">
          <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>
          <div class="form-group">
            <%= link_to new_shop_path, class: 'btn btn-primary' do %>
              Añadir <i class="fa fa-plus"></i>
            <% end %>
          </div>
          <table id="example" class="display table-border" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Dirección</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <% @shops.each do |shop| %>
                  <tr>
                      <td><%= shop.name %></td>
                      <td><%= shop.address %></td>
                      <td>
                        <a class="btn btn-sm">
                          <i class="fa fa-check-square-o"></i> Aprobar
                        </a>
                        <%= link_to edit_shop_path(shop), class: 'btn btn-sm' do %>
                          <i class="fa fa-edit"></i>  Editar
                        <% end %>
                        <a class="btn btn-sm">
                          <i class="fa fa-trash-o"></i> Borrar
                        </a>
                      </td>
                  </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>
<script type="text/javascript">
  $(document).ready(function() {
    $('#example').DataTable();
  });
</script>

app/views/site/_sidebar.html.erb
<div class="col-md-3 sidebar-right">
  <div class="item-sidebar">
    <h2 id="title">Próximos Eventos</h2>
    <% @events.each do |event| %>
      <div class="event">
        <h2><%= event.title %></h2>
        <div class="event-meta">
          <p><i class="fa fa-calendar"></i> <%= event.date %></p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</p>
        </div>
      </div>
    <% end %>
  </div>
</div>